# Generated by Django 5.2.1 on 2025-05-17 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlist_covers/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Трек в плейлисте',
                'verbose_name_plural': 'Треки в плейлисте',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('audio_file', models.FileField(upload_to='tracks/', verbose_name='Аудио файл')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (в секундах)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='Количество воспроизведений')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('audio_features', models.JSONField(blank=True, null=True, verbose_name='Аудио характеристики')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTrackInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('play', 'Проигрывание'), ('like', 'Лайк'), ('dislike', 'Дизлайк'), ('skip', 'Пропуск'), ('add_to_playlist', 'Добавление в плейлист'), ('share', 'Поделиться')], max_length=20, verbose_name='Тип взаимодействия')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('interaction_data', models.JSONField(blank=True, null=True, verbose_name='Данные взаимодействия')),
                ('listen_percentage', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Процент прослушивания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Взаимодействие с треком',
                'verbose_name_plural': 'Взаимодействия с треками',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('timestamp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Временная метка (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tracks.comment', verbose_name='Родительский комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
    ]
